// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzCTLF3nFz-I8b5QWz9O1sdyFncg5KpgE',
    appId: '1:214708430372:web:ae6d17efb166beec305ab1',
    messagingSenderId: '214708430372',
    projectId: 'pavim-daafc',
    authDomain: 'pavim-daafc.firebaseapp.com',
    storageBucket: 'pavim-daafc.firebasestorage.app',
    measurementId: 'G-3V2DT1VNBM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2NuMESZ5kiN58pitfl3D-mDO1XG8VSv8',
    appId: '1:214708430372:android:8951b9137141ca1e305ab1',
    messagingSenderId: '214708430372',
    projectId: 'pavim-daafc',
    storageBucket: 'pavim-daafc.firebasestorage.app',
  );

}